name: safeorenv
channels:
  - pytorch
  - conda-forge


dependencies:
  - python=3.10
  - pip

  # scientific stack
  - numpy=1.26.4
  - pandas
  - scipy
  - pyyaml
  - pyomo
  - gymnasium

  # torch (only once)
  - pytorch>=1.10

  - pip:
      - omnisafe